### ISSUE TITLE
New code execution failure

### ISSUE THREAD

**Issue by JuanCab** [sevenian3/ChromaStarPy#3]
Attempting to run the code produced:

`Traceback (most recent call last):
  File "ChromaStarGasPy.py", line 139, in <module>
    import CSGas
  File "/Users/xxx/ChromaStarPy/CSGas.py", line 89, in <module>
    import Dgesl
  File "/Users/xxx/ChromaStarPy/Dgesl.py", line 18, in <module>
    import Daxpy
ModuleNotFoundError: No module named 'Daxpy'`

The problem is clear, there is no `Daxpy.py` file to import.

**Comment by sevenian3** [comment]
Thanks, Juan!   You're right - the distribution was incomplete - both here and at http://www.ap.smu.ca/~ishort/OpenStars/ChromaStarGasPy.tar.gz

  I've supplied the missing files and just tested it for hot and cool stars.   I think it's all there now, both in the GitHub repo and in the public tar.gz distro. 
   
  Thanks for letting me know.  

  Ian

**Comment by sevenian3** [comment]
Thanks, Juan! You're right - the distribution was incomplete - both here
and at http://www.ap.smu.ca/~ishort/OpenStars/ChromaStarGasPy.tar.gz

I've supplied the missing files and just tested it for hot and cool stars.
I think it's all there now, both in the GitHub repo and in the public
tar.gz distro.

Thanks for letting me know.

Ian

**Comment by JuanCab** [comment]
OK, the new distribution includes a few 'dated' files in it (specifically

> ChromaStarGasPyJul42019.py
> ChromaStarPy.py.bak23Oct2017.py
> ChromaStarPyBak.py
> KappasRaylJuly42019.py
)
and still appears to be missing a file since execution failed due to 
```
  File "ChromaStarPy.py", line 96, in <module>
    import LevelPopsServer
ModuleNotFoundError: No module named 'LevelPopsServer'
```

**Comment by sevenian3** [comment]
Thanks for your continuing patience, Juan.

   I guess you were trying to start by running ChromaStarPy as the main
program.  It's been deprecated - the new main program is ChromaStarGasPy -
it calls LevelPopsGasServer (the old LevelPopsServer has been deprecated.)

  The tarball at
http://www.ap.smu.ca/~ishort/OpenStars/ChromaStarGasPy.tar.gz is a more
reliable distribution - the GitHub repository tends to accumulate all kinds
of stuff.  I've cleaned it up just now to remove these deprecated files -
sorry for the confusion.  I've updated the README accordingly.

 Ian
